/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TourRouteImport } from './routes/tour'
import { Route as SubmitEventRouteImport } from './routes/submit-event'
import { Route as SigninRouteImport } from './routes/signin'
import { Route as SetupRouteImport } from './routes/setup'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as McpRouteImport } from './routes/mcp'
import { Route as LoginRouteImport } from './routes/login'
import { Route as EventsRouteImport } from './routes/events'
import { Route as EmbedRouteImport } from './routes/embed'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as MarketingUnsubscribeRouteImport } from './routes/marketing.unsubscribe'
import { Route as MarketingSubscribeRouteImport } from './routes/marketing.subscribe'
import { Route as MarketingConfirmRouteImport } from './routes/marketing.confirm'
import { Route as InviteTokenRouteImport } from './routes/invite.$token'
import { Route as EventsIdRouteImport } from './routes/events.$id'
import { Route as CSlugRouteImport } from './routes/c.$slug'
import { Route as AuthCallbackRouteImport } from './routes/auth.callback'
import { Route as AuthenticatedSubmissionsRouteImport } from './routes/_authenticated/submissions'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedSearchRouteImport } from './routes/_authenticated/search'
import { Route as AuthenticatedMapRouteImport } from './routes/_authenticated/map'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedCalendarRouteImport } from './routes/_authenticated/calendar'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as Char91DotwellKnownChar93OauthProtectedResourceRouteImport } from './routes/[.well-known]/oauth-protected-resource'
import { Route as ApiV1IndexRouteImport } from './routes/api/v1/index'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin.index'
import { Route as CSlugSpeakersRouteImport } from './routes/c.$slug_.speakers'
import { Route as ApiV1VenuesRouteImport } from './routes/api/v1/venues'
import { Route as ApiV1MeRouteImport } from './routes/api/v1/me'
import { Route as ApiV1EventsRouteImport } from './routes/api/v1/events'
import { Route as ApiStripeWebhookRouteImport } from './routes/api/stripe.webhook'
import { Route as ApiEmbedSlugRouteImport } from './routes/api/embed.$slug'
import { Route as ApiCronEmailRemindersRouteImport } from './routes/api/cron.email-reminders'
import { Route as AuthenticatedCoordinatorSubmissionsRouteImport } from './routes/_authenticated/coordinator.submissions'
import { Route as AuthenticatedAdminUsersRouteImport } from './routes/_authenticated/admin.users'
import { Route as AuthenticatedAdminSponsorshipRouteImport } from './routes/_authenticated/admin.sponsorship'
import { Route as AuthenticatedAdminSetupRouteImport } from './routes/_authenticated/admin.setup'
import { Route as AuthenticatedAdminModerationRouteImport } from './routes/_authenticated/admin.moderation'
import { Route as AuthenticatedAdminBillingRouteImport } from './routes/_authenticated/admin.billing'
import { Route as AuthenticatedAdminAuditRouteImport } from './routes/_authenticated/admin.audit'
import { Route as DotlovableOauthConsentRouteImport } from './routes/[.]lovable.oauth.consent'
import { Route as CSlugPIdRouteImport } from './routes/c.$slug_.p.$id'
import { Route as ApiV1VenuesIdRouteImport } from './routes/api/v1/venues.$id'
import { Route as ApiV1EventsIdRouteImport } from './routes/api/v1/events.$id'
import { Route as ApiPublicIcalTokenRouteImport } from './routes/api/public/ical.$token'
import { Route as ApiAdISlotIdRouteImport } from './routes/api/ad.i.$slotId'
import { Route as ApiAdCSlotIdRouteImport } from './routes/api/ad.c.$slotId'
import { Route as AuthenticatedEventsIdManageRouteImport } from './routes/_authenticated/events.$id.manage'
import { Route as AuthenticatedEventsIdCheckinMobileRouteImport } from './routes/_authenticated/events.$id.checkin-mobile'
import { Route as AuthenticatedEventsIdCheckinRouteImport } from './routes/_authenticated/events.$id.checkin'
import { Route as AuthenticatedEventsIdAnalyticsRouteImport } from './routes/_authenticated/events.$id.analytics'
import { Route as AuthenticatedCoordinatorSettingsVenuesRouteImport } from './routes/_authenticated/coordinator.settings.venues'
import { Route as AuthenticatedCoordinatorSettingsStylingRouteImport } from './routes/_authenticated/coordinator.settings.styling'
import { Route as AuthenticatedCoordinatorSettingsOrganizersRouteImport } from './routes/_authenticated/coordinator.settings.organizers'
import { Route as AuthenticatedCoordinatorSettingsEmbedRouteImport } from './routes/_authenticated/coordinator.settings.embed'
import { Route as AuthenticatedCoordinatorSettingsCustomFieldsRouteImport } from './routes/_authenticated/coordinator.settings.custom-fields'
import { Route as AuthenticatedCoordinatorSettingsBrandingRouteImport } from './routes/_authenticated/coordinator.settings.branding'
import { Route as ApiV1EventsIdTicketsRouteImport } from './routes/api/v1/events.$id.tickets'
import { Route as ApiV1EventsIdRsvpsRouteImport } from './routes/api/v1/events.$id.rsvps'
import { Route as ApiV1EventsIdTicketsTicketIdRouteImport } from './routes/api/v1/events.$id.tickets.$ticketId'

const TourRoute = TourRouteImport.update({
  id: '/tour',
  path: '/tour',
  getParentRoute: () => rootRouteImport,
} as any)
const SubmitEventRoute = SubmitEventRouteImport.update({
  id: '/submit-event',
  path: '/submit-event',
  getParentRoute: () => rootRouteImport,
} as any)
const SigninRoute = SigninRouteImport.update({
  id: '/signin',
  path: '/signin',
  getParentRoute: () => rootRouteImport,
} as any)
const SetupRoute = SetupRouteImport.update({
  id: '/setup',
  path: '/setup',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const McpRoute = McpRouteImport.update({
  id: '/mcp',
  path: '/mcp',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsRoute = EventsRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => rootRouteImport,
} as any)
const EmbedRoute = EmbedRouteImport.update({
  id: '/embed',
  path: '/embed',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketingUnsubscribeRoute = MarketingUnsubscribeRouteImport.update({
  id: '/marketing/unsubscribe',
  path: '/marketing/unsubscribe',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketingSubscribeRoute = MarketingSubscribeRouteImport.update({
  id: '/marketing/subscribe',
  path: '/marketing/subscribe',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketingConfirmRoute = MarketingConfirmRouteImport.update({
  id: '/marketing/confirm',
  path: '/marketing/confirm',
  getParentRoute: () => rootRouteImport,
} as any)
const InviteTokenRoute = InviteTokenRouteImport.update({
  id: '/invite/$token',
  path: '/invite/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsIdRoute = EventsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => EventsRoute,
} as any)
const CSlugRoute = CSlugRouteImport.update({
  id: '/c/$slug',
  path: '/c/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/callback',
  path: '/callback',
  getParentRoute: () => AuthRoute,
} as any)
const AuthenticatedSubmissionsRoute =
  AuthenticatedSubmissionsRouteImport.update({
    id: '/submissions',
    path: '/submissions',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSearchRoute = AuthenticatedSearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMapRoute = AuthenticatedMapRouteImport.update({
  id: '/map',
  path: '/map',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCalendarRoute = AuthenticatedCalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const Char91DotwellKnownChar93OauthProtectedResourceRoute =
  Char91DotwellKnownChar93OauthProtectedResourceRouteImport.update({
    id: '/.well-known/oauth-protected-resource',
    path: '/.well-known/oauth-protected-resource',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiV1IndexRoute = ApiV1IndexRouteImport.update({
  id: '/api/v1/',
  path: '/api/v1/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const CSlugSpeakersRoute = CSlugSpeakersRouteImport.update({
  id: '/c/$slug_/speakers',
  path: '/c/$slug/speakers',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1VenuesRoute = ApiV1VenuesRouteImport.update({
  id: '/api/v1/venues',
  path: '/api/v1/venues',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1MeRoute = ApiV1MeRouteImport.update({
  id: '/api/v1/me',
  path: '/api/v1/me',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1EventsRoute = ApiV1EventsRouteImport.update({
  id: '/api/v1/events',
  path: '/api/v1/events',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiStripeWebhookRoute = ApiStripeWebhookRouteImport.update({
  id: '/api/stripe/webhook',
  path: '/api/stripe/webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiEmbedSlugRoute = ApiEmbedSlugRouteImport.update({
  id: '/api/embed/$slug',
  path: '/api/embed/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCronEmailRemindersRoute = ApiCronEmailRemindersRouteImport.update({
  id: '/api/cron/email-reminders',
  path: '/api/cron/email-reminders',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedCoordinatorSubmissionsRoute =
  AuthenticatedCoordinatorSubmissionsRouteImport.update({
    id: '/coordinator/submissions',
    path: '/coordinator/submissions',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminUsersRoute = AuthenticatedAdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminSponsorshipRoute =
  AuthenticatedAdminSponsorshipRouteImport.update({
    id: '/sponsorship',
    path: '/sponsorship',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminSetupRoute = AuthenticatedAdminSetupRouteImport.update({
  id: '/setup',
  path: '/setup',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminModerationRoute =
  AuthenticatedAdminModerationRouteImport.update({
    id: '/moderation',
    path: '/moderation',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminBillingRoute =
  AuthenticatedAdminBillingRouteImport.update({
    id: '/billing',
    path: '/billing',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminAuditRoute = AuthenticatedAdminAuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const DotlovableOauthConsentRoute = DotlovableOauthConsentRouteImport.update({
  id: '/.lovable/oauth/consent',
  path: '/.lovable/oauth/consent',
  getParentRoute: () => rootRouteImport,
} as any)
const CSlugPIdRoute = CSlugPIdRouteImport.update({
  id: '/c/$slug_/p/$id',
  path: '/c/$slug/p/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1VenuesIdRoute = ApiV1VenuesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ApiV1VenuesRoute,
} as any)
const ApiV1EventsIdRoute = ApiV1EventsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ApiV1EventsRoute,
} as any)
const ApiPublicIcalTokenRoute = ApiPublicIcalTokenRouteImport.update({
  id: '/api/public/ical/$token',
  path: '/api/public/ical/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdISlotIdRoute = ApiAdISlotIdRouteImport.update({
  id: '/api/ad/i/$slotId',
  path: '/api/ad/i/$slotId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdCSlotIdRoute = ApiAdCSlotIdRouteImport.update({
  id: '/api/ad/c/$slotId',
  path: '/api/ad/c/$slotId',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedEventsIdManageRoute =
  AuthenticatedEventsIdManageRouteImport.update({
    id: '/events/$id/manage',
    path: '/events/$id/manage',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedEventsIdCheckinMobileRoute =
  AuthenticatedEventsIdCheckinMobileRouteImport.update({
    id: '/events/$id/checkin-mobile',
    path: '/events/$id/checkin-mobile',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedEventsIdCheckinRoute =
  AuthenticatedEventsIdCheckinRouteImport.update({
    id: '/events/$id/checkin',
    path: '/events/$id/checkin',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedEventsIdAnalyticsRoute =
  AuthenticatedEventsIdAnalyticsRouteImport.update({
    id: '/events/$id/analytics',
    path: '/events/$id/analytics',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedCoordinatorSettingsVenuesRoute =
  AuthenticatedCoordinatorSettingsVenuesRouteImport.update({
    id: '/coordinator/settings/venues',
    path: '/coordinator/settings/venues',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedCoordinatorSettingsStylingRoute =
  AuthenticatedCoordinatorSettingsStylingRouteImport.update({
    id: '/coordinator/settings/styling',
    path: '/coordinator/settings/styling',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedCoordinatorSettingsOrganizersRoute =
  AuthenticatedCoordinatorSettingsOrganizersRouteImport.update({
    id: '/coordinator/settings/organizers',
    path: '/coordinator/settings/organizers',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedCoordinatorSettingsEmbedRoute =
  AuthenticatedCoordinatorSettingsEmbedRouteImport.update({
    id: '/coordinator/settings/embed',
    path: '/coordinator/settings/embed',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedCoordinatorSettingsCustomFieldsRoute =
  AuthenticatedCoordinatorSettingsCustomFieldsRouteImport.update({
    id: '/coordinator/settings/custom-fields',
    path: '/coordinator/settings/custom-fields',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedCoordinatorSettingsBrandingRoute =
  AuthenticatedCoordinatorSettingsBrandingRouteImport.update({
    id: '/coordinator/settings/branding',
    path: '/coordinator/settings/branding',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const ApiV1EventsIdTicketsRoute = ApiV1EventsIdTicketsRouteImport.update({
  id: '/tickets',
  path: '/tickets',
  getParentRoute: () => ApiV1EventsIdRoute,
} as any)
const ApiV1EventsIdRsvpsRoute = ApiV1EventsIdRsvpsRouteImport.update({
  id: '/rsvps',
  path: '/rsvps',
  getParentRoute: () => ApiV1EventsIdRoute,
} as any)
const ApiV1EventsIdTicketsTicketIdRoute =
  ApiV1EventsIdTicketsTicketIdRouteImport.update({
    id: '/$ticketId',
    path: '/$ticketId',
    getParentRoute: () => ApiV1EventsIdTicketsRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRouteWithChildren
  '/embed': typeof EmbedRoute
  '/events': typeof EventsRouteWithChildren
  '/login': typeof LoginRoute
  '/mcp': typeof McpRoute
  '/onboarding': typeof OnboardingRoute
  '/setup': typeof SetupRoute
  '/signin': typeof SigninRoute
  '/submit-event': typeof SubmitEventRoute
  '/tour': typeof TourRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/admin': typeof AuthenticatedAdminRouteWithChildren
  '/calendar': typeof AuthenticatedCalendarRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/map': typeof AuthenticatedMapRoute
  '/search': typeof AuthenticatedSearchRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/submissions': typeof AuthenticatedSubmissionsRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/c/$slug': typeof CSlugRoute
  '/events/$id': typeof EventsIdRoute
  '/invite/$token': typeof InviteTokenRoute
  '/marketing/confirm': typeof MarketingConfirmRoute
  '/marketing/subscribe': typeof MarketingSubscribeRoute
  '/marketing/unsubscribe': typeof MarketingUnsubscribeRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/admin/audit': typeof AuthenticatedAdminAuditRoute
  '/admin/billing': typeof AuthenticatedAdminBillingRoute
  '/admin/moderation': typeof AuthenticatedAdminModerationRoute
  '/admin/setup': typeof AuthenticatedAdminSetupRoute
  '/admin/sponsorship': typeof AuthenticatedAdminSponsorshipRoute
  '/admin/users': typeof AuthenticatedAdminUsersRoute
  '/coordinator/submissions': typeof AuthenticatedCoordinatorSubmissionsRoute
  '/api/cron/email-reminders': typeof ApiCronEmailRemindersRoute
  '/api/embed/$slug': typeof ApiEmbedSlugRoute
  '/api/stripe/webhook': typeof ApiStripeWebhookRoute
  '/api/v1/events': typeof ApiV1EventsRouteWithChildren
  '/api/v1/me': typeof ApiV1MeRoute
  '/api/v1/venues': typeof ApiV1VenuesRouteWithChildren
  '/c/$slug/speakers': typeof CSlugSpeakersRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
  '/api/v1/': typeof ApiV1IndexRoute
  '/coordinator/settings/branding': typeof AuthenticatedCoordinatorSettingsBrandingRoute
  '/coordinator/settings/custom-fields': typeof AuthenticatedCoordinatorSettingsCustomFieldsRoute
  '/coordinator/settings/embed': typeof AuthenticatedCoordinatorSettingsEmbedRoute
  '/coordinator/settings/organizers': typeof AuthenticatedCoordinatorSettingsOrganizersRoute
  '/coordinator/settings/styling': typeof AuthenticatedCoordinatorSettingsStylingRoute
  '/coordinator/settings/venues': typeof AuthenticatedCoordinatorSettingsVenuesRoute
  '/events/$id/analytics': typeof AuthenticatedEventsIdAnalyticsRoute
  '/events/$id/checkin': typeof AuthenticatedEventsIdCheckinRoute
  '/events/$id/checkin-mobile': typeof AuthenticatedEventsIdCheckinMobileRoute
  '/events/$id/manage': typeof AuthenticatedEventsIdManageRoute
  '/api/ad/c/$slotId': typeof ApiAdCSlotIdRoute
  '/api/ad/i/$slotId': typeof ApiAdISlotIdRoute
  '/api/public/ical/$token': typeof ApiPublicIcalTokenRoute
  '/api/v1/events/$id': typeof ApiV1EventsIdRouteWithChildren
  '/api/v1/venues/$id': typeof ApiV1VenuesIdRoute
  '/c/$slug/p/$id': typeof CSlugPIdRoute
  '/api/v1/events/$id/rsvps': typeof ApiV1EventsIdRsvpsRoute
  '/api/v1/events/$id/tickets': typeof ApiV1EventsIdTicketsRouteWithChildren
  '/api/v1/events/$id/tickets/$ticketId': typeof ApiV1EventsIdTicketsTicketIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRouteWithChildren
  '/embed': typeof EmbedRoute
  '/events': typeof EventsRouteWithChildren
  '/login': typeof LoginRoute
  '/mcp': typeof McpRoute
  '/onboarding': typeof OnboardingRoute
  '/setup': typeof SetupRoute
  '/signin': typeof SigninRoute
  '/submit-event': typeof SubmitEventRoute
  '/tour': typeof TourRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/calendar': typeof AuthenticatedCalendarRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/map': typeof AuthenticatedMapRoute
  '/search': typeof AuthenticatedSearchRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/submissions': typeof AuthenticatedSubmissionsRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/c/$slug': typeof CSlugRoute
  '/events/$id': typeof EventsIdRoute
  '/invite/$token': typeof InviteTokenRoute
  '/marketing/confirm': typeof MarketingConfirmRoute
  '/marketing/subscribe': typeof MarketingSubscribeRoute
  '/marketing/unsubscribe': typeof MarketingUnsubscribeRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/admin/audit': typeof AuthenticatedAdminAuditRoute
  '/admin/billing': typeof AuthenticatedAdminBillingRoute
  '/admin/moderation': typeof AuthenticatedAdminModerationRoute
  '/admin/setup': typeof AuthenticatedAdminSetupRoute
  '/admin/sponsorship': typeof AuthenticatedAdminSponsorshipRoute
  '/admin/users': typeof AuthenticatedAdminUsersRoute
  '/coordinator/submissions': typeof AuthenticatedCoordinatorSubmissionsRoute
  '/api/cron/email-reminders': typeof ApiCronEmailRemindersRoute
  '/api/embed/$slug': typeof ApiEmbedSlugRoute
  '/api/stripe/webhook': typeof ApiStripeWebhookRoute
  '/api/v1/events': typeof ApiV1EventsRouteWithChildren
  '/api/v1/me': typeof ApiV1MeRoute
  '/api/v1/venues': typeof ApiV1VenuesRouteWithChildren
  '/c/$slug/speakers': typeof CSlugSpeakersRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
  '/api/v1': typeof ApiV1IndexRoute
  '/coordinator/settings/branding': typeof AuthenticatedCoordinatorSettingsBrandingRoute
  '/coordinator/settings/custom-fields': typeof AuthenticatedCoordinatorSettingsCustomFieldsRoute
  '/coordinator/settings/embed': typeof AuthenticatedCoordinatorSettingsEmbedRoute
  '/coordinator/settings/organizers': typeof AuthenticatedCoordinatorSettingsOrganizersRoute
  '/coordinator/settings/styling': typeof AuthenticatedCoordinatorSettingsStylingRoute
  '/coordinator/settings/venues': typeof AuthenticatedCoordinatorSettingsVenuesRoute
  '/events/$id/analytics': typeof AuthenticatedEventsIdAnalyticsRoute
  '/events/$id/checkin': typeof AuthenticatedEventsIdCheckinRoute
  '/events/$id/checkin-mobile': typeof AuthenticatedEventsIdCheckinMobileRoute
  '/events/$id/manage': typeof AuthenticatedEventsIdManageRoute
  '/api/ad/c/$slotId': typeof ApiAdCSlotIdRoute
  '/api/ad/i/$slotId': typeof ApiAdISlotIdRoute
  '/api/public/ical/$token': typeof ApiPublicIcalTokenRoute
  '/api/v1/events/$id': typeof ApiV1EventsIdRouteWithChildren
  '/api/v1/venues/$id': typeof ApiV1VenuesIdRoute
  '/c/$slug/p/$id': typeof CSlugPIdRoute
  '/api/v1/events/$id/rsvps': typeof ApiV1EventsIdRsvpsRoute
  '/api/v1/events/$id/tickets': typeof ApiV1EventsIdTicketsRouteWithChildren
  '/api/v1/events/$id/tickets/$ticketId': typeof ApiV1EventsIdTicketsTicketIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRouteWithChildren
  '/embed': typeof EmbedRoute
  '/events': typeof EventsRouteWithChildren
  '/login': typeof LoginRoute
  '/mcp': typeof McpRoute
  '/onboarding': typeof OnboardingRoute
  '/setup': typeof SetupRoute
  '/signin': typeof SigninRoute
  '/submit-event': typeof SubmitEventRoute
  '/tour': typeof TourRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRouteWithChildren
  '/_authenticated/calendar': typeof AuthenticatedCalendarRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/map': typeof AuthenticatedMapRoute
  '/_authenticated/search': typeof AuthenticatedSearchRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/_authenticated/submissions': typeof AuthenticatedSubmissionsRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/c/$slug': typeof CSlugRoute
  '/events/$id': typeof EventsIdRoute
  '/invite/$token': typeof InviteTokenRoute
  '/marketing/confirm': typeof MarketingConfirmRoute
  '/marketing/subscribe': typeof MarketingSubscribeRoute
  '/marketing/unsubscribe': typeof MarketingUnsubscribeRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/_authenticated/admin/audit': typeof AuthenticatedAdminAuditRoute
  '/_authenticated/admin/billing': typeof AuthenticatedAdminBillingRoute
  '/_authenticated/admin/moderation': typeof AuthenticatedAdminModerationRoute
  '/_authenticated/admin/setup': typeof AuthenticatedAdminSetupRoute
  '/_authenticated/admin/sponsorship': typeof AuthenticatedAdminSponsorshipRoute
  '/_authenticated/admin/users': typeof AuthenticatedAdminUsersRoute
  '/_authenticated/coordinator/submissions': typeof AuthenticatedCoordinatorSubmissionsRoute
  '/api/cron/email-reminders': typeof ApiCronEmailRemindersRoute
  '/api/embed/$slug': typeof ApiEmbedSlugRoute
  '/api/stripe/webhook': typeof ApiStripeWebhookRoute
  '/api/v1/events': typeof ApiV1EventsRouteWithChildren
  '/api/v1/me': typeof ApiV1MeRoute
  '/api/v1/venues': typeof ApiV1VenuesRouteWithChildren
  '/c/$slug_/speakers': typeof CSlugSpeakersRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
  '/api/v1/': typeof ApiV1IndexRoute
  '/_authenticated/coordinator/settings/branding': typeof AuthenticatedCoordinatorSettingsBrandingRoute
  '/_authenticated/coordinator/settings/custom-fields': typeof AuthenticatedCoordinatorSettingsCustomFieldsRoute
  '/_authenticated/coordinator/settings/embed': typeof AuthenticatedCoordinatorSettingsEmbedRoute
  '/_authenticated/coordinator/settings/organizers': typeof AuthenticatedCoordinatorSettingsOrganizersRoute
  '/_authenticated/coordinator/settings/styling': typeof AuthenticatedCoordinatorSettingsStylingRoute
  '/_authenticated/coordinator/settings/venues': typeof AuthenticatedCoordinatorSettingsVenuesRoute
  '/_authenticated/events/$id/analytics': typeof AuthenticatedEventsIdAnalyticsRoute
  '/_authenticated/events/$id/checkin': typeof AuthenticatedEventsIdCheckinRoute
  '/_authenticated/events/$id/checkin-mobile': typeof AuthenticatedEventsIdCheckinMobileRoute
  '/_authenticated/events/$id/manage': typeof AuthenticatedEventsIdManageRoute
  '/api/ad/c/$slotId': typeof ApiAdCSlotIdRoute
  '/api/ad/i/$slotId': typeof ApiAdISlotIdRoute
  '/api/public/ical/$token': typeof ApiPublicIcalTokenRoute
  '/api/v1/events/$id': typeof ApiV1EventsIdRouteWithChildren
  '/api/v1/venues/$id': typeof ApiV1VenuesIdRoute
  '/c/$slug_/p/$id': typeof CSlugPIdRoute
  '/api/v1/events/$id/rsvps': typeof ApiV1EventsIdRsvpsRoute
  '/api/v1/events/$id/tickets': typeof ApiV1EventsIdTicketsRouteWithChildren
  '/api/v1/events/$id/tickets/$ticketId': typeof ApiV1EventsIdTicketsTicketIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/embed'
    | '/events'
    | '/login'
    | '/mcp'
    | '/onboarding'
    | '/setup'
    | '/signin'
    | '/submit-event'
    | '/tour'
    | '/.well-known/oauth-protected-resource'
    | '/admin'
    | '/calendar'
    | '/dashboard'
    | '/map'
    | '/search'
    | '/settings'
    | '/submissions'
    | '/auth/callback'
    | '/c/$slug'
    | '/events/$id'
    | '/invite/$token'
    | '/marketing/confirm'
    | '/marketing/subscribe'
    | '/marketing/unsubscribe'
    | '/.lovable/oauth/consent'
    | '/admin/audit'
    | '/admin/billing'
    | '/admin/moderation'
    | '/admin/setup'
    | '/admin/sponsorship'
    | '/admin/users'
    | '/coordinator/submissions'
    | '/api/cron/email-reminders'
    | '/api/embed/$slug'
    | '/api/stripe/webhook'
    | '/api/v1/events'
    | '/api/v1/me'
    | '/api/v1/venues'
    | '/c/$slug/speakers'
    | '/admin/'
    | '/api/v1/'
    | '/coordinator/settings/branding'
    | '/coordinator/settings/custom-fields'
    | '/coordinator/settings/embed'
    | '/coordinator/settings/organizers'
    | '/coordinator/settings/styling'
    | '/coordinator/settings/venues'
    | '/events/$id/analytics'
    | '/events/$id/checkin'
    | '/events/$id/checkin-mobile'
    | '/events/$id/manage'
    | '/api/ad/c/$slotId'
    | '/api/ad/i/$slotId'
    | '/api/public/ical/$token'
    | '/api/v1/events/$id'
    | '/api/v1/venues/$id'
    | '/c/$slug/p/$id'
    | '/api/v1/events/$id/rsvps'
    | '/api/v1/events/$id/tickets'
    | '/api/v1/events/$id/tickets/$ticketId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/embed'
    | '/events'
    | '/login'
    | '/mcp'
    | '/onboarding'
    | '/setup'
    | '/signin'
    | '/submit-event'
    | '/tour'
    | '/.well-known/oauth-protected-resource'
    | '/calendar'
    | '/dashboard'
    | '/map'
    | '/search'
    | '/settings'
    | '/submissions'
    | '/auth/callback'
    | '/c/$slug'
    | '/events/$id'
    | '/invite/$token'
    | '/marketing/confirm'
    | '/marketing/subscribe'
    | '/marketing/unsubscribe'
    | '/.lovable/oauth/consent'
    | '/admin/audit'
    | '/admin/billing'
    | '/admin/moderation'
    | '/admin/setup'
    | '/admin/sponsorship'
    | '/admin/users'
    | '/coordinator/submissions'
    | '/api/cron/email-reminders'
    | '/api/embed/$slug'
    | '/api/stripe/webhook'
    | '/api/v1/events'
    | '/api/v1/me'
    | '/api/v1/venues'
    | '/c/$slug/speakers'
    | '/admin'
    | '/api/v1'
    | '/coordinator/settings/branding'
    | '/coordinator/settings/custom-fields'
    | '/coordinator/settings/embed'
    | '/coordinator/settings/organizers'
    | '/coordinator/settings/styling'
    | '/coordinator/settings/venues'
    | '/events/$id/analytics'
    | '/events/$id/checkin'
    | '/events/$id/checkin-mobile'
    | '/events/$id/manage'
    | '/api/ad/c/$slotId'
    | '/api/ad/i/$slotId'
    | '/api/public/ical/$token'
    | '/api/v1/events/$id'
    | '/api/v1/venues/$id'
    | '/c/$slug/p/$id'
    | '/api/v1/events/$id/rsvps'
    | '/api/v1/events/$id/tickets'
    | '/api/v1/events/$id/tickets/$ticketId'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/embed'
    | '/events'
    | '/login'
    | '/mcp'
    | '/onboarding'
    | '/setup'
    | '/signin'
    | '/submit-event'
    | '/tour'
    | '/.well-known/oauth-protected-resource'
    | '/_authenticated/admin'
    | '/_authenticated/calendar'
    | '/_authenticated/dashboard'
    | '/_authenticated/map'
    | '/_authenticated/search'
    | '/_authenticated/settings'
    | '/_authenticated/submissions'
    | '/auth/callback'
    | '/c/$slug'
    | '/events/$id'
    | '/invite/$token'
    | '/marketing/confirm'
    | '/marketing/subscribe'
    | '/marketing/unsubscribe'
    | '/.lovable/oauth/consent'
    | '/_authenticated/admin/audit'
    | '/_authenticated/admin/billing'
    | '/_authenticated/admin/moderation'
    | '/_authenticated/admin/setup'
    | '/_authenticated/admin/sponsorship'
    | '/_authenticated/admin/users'
    | '/_authenticated/coordinator/submissions'
    | '/api/cron/email-reminders'
    | '/api/embed/$slug'
    | '/api/stripe/webhook'
    | '/api/v1/events'
    | '/api/v1/me'
    | '/api/v1/venues'
    | '/c/$slug_/speakers'
    | '/_authenticated/admin/'
    | '/api/v1/'
    | '/_authenticated/coordinator/settings/branding'
    | '/_authenticated/coordinator/settings/custom-fields'
    | '/_authenticated/coordinator/settings/embed'
    | '/_authenticated/coordinator/settings/organizers'
    | '/_authenticated/coordinator/settings/styling'
    | '/_authenticated/coordinator/settings/venues'
    | '/_authenticated/events/$id/analytics'
    | '/_authenticated/events/$id/checkin'
    | '/_authenticated/events/$id/checkin-mobile'
    | '/_authenticated/events/$id/manage'
    | '/api/ad/c/$slotId'
    | '/api/ad/i/$slotId'
    | '/api/public/ical/$token'
    | '/api/v1/events/$id'
    | '/api/v1/venues/$id'
    | '/c/$slug_/p/$id'
    | '/api/v1/events/$id/rsvps'
    | '/api/v1/events/$id/tickets'
    | '/api/v1/events/$id/tickets/$ticketId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRouteWithChildren
  EmbedRoute: typeof EmbedRoute
  EventsRoute: typeof EventsRouteWithChildren
  LoginRoute: typeof LoginRoute
  McpRoute: typeof McpRoute
  OnboardingRoute: typeof OnboardingRoute
  SetupRoute: typeof SetupRoute
  SigninRoute: typeof SigninRoute
  SubmitEventRoute: typeof SubmitEventRoute
  TourRoute: typeof TourRoute
  Char91DotwellKnownChar93OauthProtectedResourceRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  CSlugRoute: typeof CSlugRoute
  InviteTokenRoute: typeof InviteTokenRoute
  MarketingConfirmRoute: typeof MarketingConfirmRoute
  MarketingSubscribeRoute: typeof MarketingSubscribeRoute
  MarketingUnsubscribeRoute: typeof MarketingUnsubscribeRoute
  DotlovableOauthConsentRoute: typeof DotlovableOauthConsentRoute
  ApiCronEmailRemindersRoute: typeof ApiCronEmailRemindersRoute
  ApiEmbedSlugRoute: typeof ApiEmbedSlugRoute
  ApiStripeWebhookRoute: typeof ApiStripeWebhookRoute
  ApiV1EventsRoute: typeof ApiV1EventsRouteWithChildren
  ApiV1MeRoute: typeof ApiV1MeRoute
  ApiV1VenuesRoute: typeof ApiV1VenuesRouteWithChildren
  CSlugSpeakersRoute: typeof CSlugSpeakersRoute
  ApiV1IndexRoute: typeof ApiV1IndexRoute
  ApiAdCSlotIdRoute: typeof ApiAdCSlotIdRoute
  ApiAdISlotIdRoute: typeof ApiAdISlotIdRoute
  ApiPublicIcalTokenRoute: typeof ApiPublicIcalTokenRoute
  CSlugPIdRoute: typeof CSlugPIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/tour': {
      id: '/tour'
      path: '/tour'
      fullPath: '/tour'
      preLoaderRoute: typeof TourRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/submit-event': {
      id: '/submit-event'
      path: '/submit-event'
      fullPath: '/submit-event'
      preLoaderRoute: typeof SubmitEventRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signin': {
      id: '/signin'
      path: '/signin'
      fullPath: '/signin'
      preLoaderRoute: typeof SigninRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/setup': {
      id: '/setup'
      path: '/setup'
      fullPath: '/setup'
      preLoaderRoute: typeof SetupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mcp': {
      id: '/mcp'
      path: '/mcp'
      fullPath: '/mcp'
      preLoaderRoute: typeof McpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events': {
      id: '/events'
      path: '/events'
      fullPath: '/events'
      preLoaderRoute: typeof EventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/embed': {
      id: '/embed'
      path: '/embed'
      fullPath: '/embed'
      preLoaderRoute: typeof EmbedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/marketing/unsubscribe': {
      id: '/marketing/unsubscribe'
      path: '/marketing/unsubscribe'
      fullPath: '/marketing/unsubscribe'
      preLoaderRoute: typeof MarketingUnsubscribeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/marketing/subscribe': {
      id: '/marketing/subscribe'
      path: '/marketing/subscribe'
      fullPath: '/marketing/subscribe'
      preLoaderRoute: typeof MarketingSubscribeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/marketing/confirm': {
      id: '/marketing/confirm'
      path: '/marketing/confirm'
      fullPath: '/marketing/confirm'
      preLoaderRoute: typeof MarketingConfirmRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invite/$token': {
      id: '/invite/$token'
      path: '/invite/$token'
      fullPath: '/invite/$token'
      preLoaderRoute: typeof InviteTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events/$id': {
      id: '/events/$id'
      path: '/$id'
      fullPath: '/events/$id'
      preLoaderRoute: typeof EventsIdRouteImport
      parentRoute: typeof EventsRoute
    }
    '/c/$slug': {
      id: '/c/$slug'
      path: '/c/$slug'
      fullPath: '/c/$slug'
      preLoaderRoute: typeof CSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_authenticated/submissions': {
      id: '/_authenticated/submissions'
      path: '/submissions'
      fullPath: '/submissions'
      preLoaderRoute: typeof AuthenticatedSubmissionsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/search': {
      id: '/_authenticated/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof AuthenticatedSearchRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/map': {
      id: '/_authenticated/map'
      path: '/map'
      fullPath: '/map'
      preLoaderRoute: typeof AuthenticatedMapRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/calendar': {
      id: '/_authenticated/calendar'
      path: '/calendar'
      fullPath: '/calendar'
      preLoaderRoute: typeof AuthenticatedCalendarRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/.well-known/oauth-protected-resource': {
      id: '/.well-known/oauth-protected-resource'
      path: '/.well-known/oauth-protected-resource'
      fullPath: '/.well-known/oauth-protected-resource'
      preLoaderRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/': {
      id: '/api/v1/'
      path: '/api/v1'
      fullPath: '/api/v1/'
      preLoaderRoute: typeof ApiV1IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/c/$slug_/speakers': {
      id: '/c/$slug_/speakers'
      path: '/c/$slug/speakers'
      fullPath: '/c/$slug/speakers'
      preLoaderRoute: typeof CSlugSpeakersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/venues': {
      id: '/api/v1/venues'
      path: '/api/v1/venues'
      fullPath: '/api/v1/venues'
      preLoaderRoute: typeof ApiV1VenuesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/me': {
      id: '/api/v1/me'
      path: '/api/v1/me'
      fullPath: '/api/v1/me'
      preLoaderRoute: typeof ApiV1MeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/events': {
      id: '/api/v1/events'
      path: '/api/v1/events'
      fullPath: '/api/v1/events'
      preLoaderRoute: typeof ApiV1EventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/stripe/webhook': {
      id: '/api/stripe/webhook'
      path: '/api/stripe/webhook'
      fullPath: '/api/stripe/webhook'
      preLoaderRoute: typeof ApiStripeWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/embed/$slug': {
      id: '/api/embed/$slug'
      path: '/api/embed/$slug'
      fullPath: '/api/embed/$slug'
      preLoaderRoute: typeof ApiEmbedSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/cron/email-reminders': {
      id: '/api/cron/email-reminders'
      path: '/api/cron/email-reminders'
      fullPath: '/api/cron/email-reminders'
      preLoaderRoute: typeof ApiCronEmailRemindersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/coordinator/submissions': {
      id: '/_authenticated/coordinator/submissions'
      path: '/coordinator/submissions'
      fullPath: '/coordinator/submissions'
      preLoaderRoute: typeof AuthenticatedCoordinatorSubmissionsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/users': {
      id: '/_authenticated/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AuthenticatedAdminUsersRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/sponsorship': {
      id: '/_authenticated/admin/sponsorship'
      path: '/sponsorship'
      fullPath: '/admin/sponsorship'
      preLoaderRoute: typeof AuthenticatedAdminSponsorshipRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/setup': {
      id: '/_authenticated/admin/setup'
      path: '/setup'
      fullPath: '/admin/setup'
      preLoaderRoute: typeof AuthenticatedAdminSetupRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/moderation': {
      id: '/_authenticated/admin/moderation'
      path: '/moderation'
      fullPath: '/admin/moderation'
      preLoaderRoute: typeof AuthenticatedAdminModerationRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/billing': {
      id: '/_authenticated/admin/billing'
      path: '/billing'
      fullPath: '/admin/billing'
      preLoaderRoute: typeof AuthenticatedAdminBillingRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/audit': {
      id: '/_authenticated/admin/audit'
      path: '/audit'
      fullPath: '/admin/audit'
      preLoaderRoute: typeof AuthenticatedAdminAuditRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/.lovable/oauth/consent': {
      id: '/.lovable/oauth/consent'
      path: '/.lovable/oauth/consent'
      fullPath: '/.lovable/oauth/consent'
      preLoaderRoute: typeof DotlovableOauthConsentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/c/$slug_/p/$id': {
      id: '/c/$slug_/p/$id'
      path: '/c/$slug/p/$id'
      fullPath: '/c/$slug/p/$id'
      preLoaderRoute: typeof CSlugPIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/venues/$id': {
      id: '/api/v1/venues/$id'
      path: '/$id'
      fullPath: '/api/v1/venues/$id'
      preLoaderRoute: typeof ApiV1VenuesIdRouteImport
      parentRoute: typeof ApiV1VenuesRoute
    }
    '/api/v1/events/$id': {
      id: '/api/v1/events/$id'
      path: '/$id'
      fullPath: '/api/v1/events/$id'
      preLoaderRoute: typeof ApiV1EventsIdRouteImport
      parentRoute: typeof ApiV1EventsRoute
    }
    '/api/public/ical/$token': {
      id: '/api/public/ical/$token'
      path: '/api/public/ical/$token'
      fullPath: '/api/public/ical/$token'
      preLoaderRoute: typeof ApiPublicIcalTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/ad/i/$slotId': {
      id: '/api/ad/i/$slotId'
      path: '/api/ad/i/$slotId'
      fullPath: '/api/ad/i/$slotId'
      preLoaderRoute: typeof ApiAdISlotIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/ad/c/$slotId': {
      id: '/api/ad/c/$slotId'
      path: '/api/ad/c/$slotId'
      fullPath: '/api/ad/c/$slotId'
      preLoaderRoute: typeof ApiAdCSlotIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/events/$id/manage': {
      id: '/_authenticated/events/$id/manage'
      path: '/events/$id/manage'
      fullPath: '/events/$id/manage'
      preLoaderRoute: typeof AuthenticatedEventsIdManageRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/events/$id/checkin-mobile': {
      id: '/_authenticated/events/$id/checkin-mobile'
      path: '/events/$id/checkin-mobile'
      fullPath: '/events/$id/checkin-mobile'
      preLoaderRoute: typeof AuthenticatedEventsIdCheckinMobileRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/events/$id/checkin': {
      id: '/_authenticated/events/$id/checkin'
      path: '/events/$id/checkin'
      fullPath: '/events/$id/checkin'
      preLoaderRoute: typeof AuthenticatedEventsIdCheckinRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/events/$id/analytics': {
      id: '/_authenticated/events/$id/analytics'
      path: '/events/$id/analytics'
      fullPath: '/events/$id/analytics'
      preLoaderRoute: typeof AuthenticatedEventsIdAnalyticsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/coordinator/settings/venues': {
      id: '/_authenticated/coordinator/settings/venues'
      path: '/coordinator/settings/venues'
      fullPath: '/coordinator/settings/venues'
      preLoaderRoute: typeof AuthenticatedCoordinatorSettingsVenuesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/coordinator/settings/styling': {
      id: '/_authenticated/coordinator/settings/styling'
      path: '/coordinator/settings/styling'
      fullPath: '/coordinator/settings/styling'
      preLoaderRoute: typeof AuthenticatedCoordinatorSettingsStylingRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/coordinator/settings/organizers': {
      id: '/_authenticated/coordinator/settings/organizers'
      path: '/coordinator/settings/organizers'
      fullPath: '/coordinator/settings/organizers'
      preLoaderRoute: typeof AuthenticatedCoordinatorSettingsOrganizersRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/coordinator/settings/embed': {
      id: '/_authenticated/coordinator/settings/embed'
      path: '/coordinator/settings/embed'
      fullPath: '/coordinator/settings/embed'
      preLoaderRoute: typeof AuthenticatedCoordinatorSettingsEmbedRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/coordinator/settings/custom-fields': {
      id: '/_authenticated/coordinator/settings/custom-fields'
      path: '/coordinator/settings/custom-fields'
      fullPath: '/coordinator/settings/custom-fields'
      preLoaderRoute: typeof AuthenticatedCoordinatorSettingsCustomFieldsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/coordinator/settings/branding': {
      id: '/_authenticated/coordinator/settings/branding'
      path: '/coordinator/settings/branding'
      fullPath: '/coordinator/settings/branding'
      preLoaderRoute: typeof AuthenticatedCoordinatorSettingsBrandingRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/v1/events/$id/tickets': {
      id: '/api/v1/events/$id/tickets'
      path: '/tickets'
      fullPath: '/api/v1/events/$id/tickets'
      preLoaderRoute: typeof ApiV1EventsIdTicketsRouteImport
      parentRoute: typeof ApiV1EventsIdRoute
    }
    '/api/v1/events/$id/rsvps': {
      id: '/api/v1/events/$id/rsvps'
      path: '/rsvps'
      fullPath: '/api/v1/events/$id/rsvps'
      preLoaderRoute: typeof ApiV1EventsIdRsvpsRouteImport
      parentRoute: typeof ApiV1EventsIdRoute
    }
    '/api/v1/events/$id/tickets/$ticketId': {
      id: '/api/v1/events/$id/tickets/$ticketId'
      path: '/$ticketId'
      fullPath: '/api/v1/events/$id/tickets/$ticketId'
      preLoaderRoute: typeof ApiV1EventsIdTicketsTicketIdRouteImport
      parentRoute: typeof ApiV1EventsIdTicketsRoute
    }
  }
}

interface AuthenticatedAdminRouteChildren {
  AuthenticatedAdminAuditRoute: typeof AuthenticatedAdminAuditRoute
  AuthenticatedAdminBillingRoute: typeof AuthenticatedAdminBillingRoute
  AuthenticatedAdminModerationRoute: typeof AuthenticatedAdminModerationRoute
  AuthenticatedAdminSetupRoute: typeof AuthenticatedAdminSetupRoute
  AuthenticatedAdminSponsorshipRoute: typeof AuthenticatedAdminSponsorshipRoute
  AuthenticatedAdminUsersRoute: typeof AuthenticatedAdminUsersRoute
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
}

const AuthenticatedAdminRouteChildren: AuthenticatedAdminRouteChildren = {
  AuthenticatedAdminAuditRoute: AuthenticatedAdminAuditRoute,
  AuthenticatedAdminBillingRoute: AuthenticatedAdminBillingRoute,
  AuthenticatedAdminModerationRoute: AuthenticatedAdminModerationRoute,
  AuthenticatedAdminSetupRoute: AuthenticatedAdminSetupRoute,
  AuthenticatedAdminSponsorshipRoute: AuthenticatedAdminSponsorshipRoute,
  AuthenticatedAdminUsersRoute: AuthenticatedAdminUsersRoute,
  AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
}

const AuthenticatedAdminRouteWithChildren =
  AuthenticatedAdminRoute._addFileChildren(AuthenticatedAdminRouteChildren)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRouteWithChildren
  AuthenticatedCalendarRoute: typeof AuthenticatedCalendarRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedMapRoute: typeof AuthenticatedMapRoute
  AuthenticatedSearchRoute: typeof AuthenticatedSearchRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedSubmissionsRoute: typeof AuthenticatedSubmissionsRoute
  AuthenticatedCoordinatorSubmissionsRoute: typeof AuthenticatedCoordinatorSubmissionsRoute
  AuthenticatedCoordinatorSettingsBrandingRoute: typeof AuthenticatedCoordinatorSettingsBrandingRoute
  AuthenticatedCoordinatorSettingsCustomFieldsRoute: typeof AuthenticatedCoordinatorSettingsCustomFieldsRoute
  AuthenticatedCoordinatorSettingsEmbedRoute: typeof AuthenticatedCoordinatorSettingsEmbedRoute
  AuthenticatedCoordinatorSettingsOrganizersRoute: typeof AuthenticatedCoordinatorSettingsOrganizersRoute
  AuthenticatedCoordinatorSettingsStylingRoute: typeof AuthenticatedCoordinatorSettingsStylingRoute
  AuthenticatedCoordinatorSettingsVenuesRoute: typeof AuthenticatedCoordinatorSettingsVenuesRoute
  AuthenticatedEventsIdAnalyticsRoute: typeof AuthenticatedEventsIdAnalyticsRoute
  AuthenticatedEventsIdCheckinRoute: typeof AuthenticatedEventsIdCheckinRoute
  AuthenticatedEventsIdCheckinMobileRoute: typeof AuthenticatedEventsIdCheckinMobileRoute
  AuthenticatedEventsIdManageRoute: typeof AuthenticatedEventsIdManageRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRouteWithChildren,
  AuthenticatedCalendarRoute: AuthenticatedCalendarRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedMapRoute: AuthenticatedMapRoute,
  AuthenticatedSearchRoute: AuthenticatedSearchRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedSubmissionsRoute: AuthenticatedSubmissionsRoute,
  AuthenticatedCoordinatorSubmissionsRoute:
    AuthenticatedCoordinatorSubmissionsRoute,
  AuthenticatedCoordinatorSettingsBrandingRoute:
    AuthenticatedCoordinatorSettingsBrandingRoute,
  AuthenticatedCoordinatorSettingsCustomFieldsRoute:
    AuthenticatedCoordinatorSettingsCustomFieldsRoute,
  AuthenticatedCoordinatorSettingsEmbedRoute:
    AuthenticatedCoordinatorSettingsEmbedRoute,
  AuthenticatedCoordinatorSettingsOrganizersRoute:
    AuthenticatedCoordinatorSettingsOrganizersRoute,
  AuthenticatedCoordinatorSettingsStylingRoute:
    AuthenticatedCoordinatorSettingsStylingRoute,
  AuthenticatedCoordinatorSettingsVenuesRoute:
    AuthenticatedCoordinatorSettingsVenuesRoute,
  AuthenticatedEventsIdAnalyticsRoute: AuthenticatedEventsIdAnalyticsRoute,
  AuthenticatedEventsIdCheckinRoute: AuthenticatedEventsIdCheckinRoute,
  AuthenticatedEventsIdCheckinMobileRoute:
    AuthenticatedEventsIdCheckinMobileRoute,
  AuthenticatedEventsIdManageRoute: AuthenticatedEventsIdManageRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface AuthRouteChildren {
  AuthCallbackRoute: typeof AuthCallbackRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthCallbackRoute: AuthCallbackRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

interface EventsRouteChildren {
  EventsIdRoute: typeof EventsIdRoute
}

const EventsRouteChildren: EventsRouteChildren = {
  EventsIdRoute: EventsIdRoute,
}

const EventsRouteWithChildren =
  EventsRoute._addFileChildren(EventsRouteChildren)

interface ApiV1EventsIdTicketsRouteChildren {
  ApiV1EventsIdTicketsTicketIdRoute: typeof ApiV1EventsIdTicketsTicketIdRoute
}

const ApiV1EventsIdTicketsRouteChildren: ApiV1EventsIdTicketsRouteChildren = {
  ApiV1EventsIdTicketsTicketIdRoute: ApiV1EventsIdTicketsTicketIdRoute,
}

const ApiV1EventsIdTicketsRouteWithChildren =
  ApiV1EventsIdTicketsRoute._addFileChildren(ApiV1EventsIdTicketsRouteChildren)

interface ApiV1EventsIdRouteChildren {
  ApiV1EventsIdRsvpsRoute: typeof ApiV1EventsIdRsvpsRoute
  ApiV1EventsIdTicketsRoute: typeof ApiV1EventsIdTicketsRouteWithChildren
}

const ApiV1EventsIdRouteChildren: ApiV1EventsIdRouteChildren = {
  ApiV1EventsIdRsvpsRoute: ApiV1EventsIdRsvpsRoute,
  ApiV1EventsIdTicketsRoute: ApiV1EventsIdTicketsRouteWithChildren,
}

const ApiV1EventsIdRouteWithChildren = ApiV1EventsIdRoute._addFileChildren(
  ApiV1EventsIdRouteChildren,
)

interface ApiV1EventsRouteChildren {
  ApiV1EventsIdRoute: typeof ApiV1EventsIdRouteWithChildren
}

const ApiV1EventsRouteChildren: ApiV1EventsRouteChildren = {
  ApiV1EventsIdRoute: ApiV1EventsIdRouteWithChildren,
}

const ApiV1EventsRouteWithChildren = ApiV1EventsRoute._addFileChildren(
  ApiV1EventsRouteChildren,
)

interface ApiV1VenuesRouteChildren {
  ApiV1VenuesIdRoute: typeof ApiV1VenuesIdRoute
}

const ApiV1VenuesRouteChildren: ApiV1VenuesRouteChildren = {
  ApiV1VenuesIdRoute: ApiV1VenuesIdRoute,
}

const ApiV1VenuesRouteWithChildren = ApiV1VenuesRoute._addFileChildren(
  ApiV1VenuesRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRouteWithChildren,
  EmbedRoute: EmbedRoute,
  EventsRoute: EventsRouteWithChildren,
  LoginRoute: LoginRoute,
  McpRoute: McpRoute,
  OnboardingRoute: OnboardingRoute,
  SetupRoute: SetupRoute,
  SigninRoute: SigninRoute,
  SubmitEventRoute: SubmitEventRoute,
  TourRoute: TourRoute,
  Char91DotwellKnownChar93OauthProtectedResourceRoute:
    Char91DotwellKnownChar93OauthProtectedResourceRoute,
  CSlugRoute: CSlugRoute,
  InviteTokenRoute: InviteTokenRoute,
  MarketingConfirmRoute: MarketingConfirmRoute,
  MarketingSubscribeRoute: MarketingSubscribeRoute,
  MarketingUnsubscribeRoute: MarketingUnsubscribeRoute,
  DotlovableOauthConsentRoute: DotlovableOauthConsentRoute,
  ApiCronEmailRemindersRoute: ApiCronEmailRemindersRoute,
  ApiEmbedSlugRoute: ApiEmbedSlugRoute,
  ApiStripeWebhookRoute: ApiStripeWebhookRoute,
  ApiV1EventsRoute: ApiV1EventsRouteWithChildren,
  ApiV1MeRoute: ApiV1MeRoute,
  ApiV1VenuesRoute: ApiV1VenuesRouteWithChildren,
  CSlugSpeakersRoute: CSlugSpeakersRoute,
  ApiV1IndexRoute: ApiV1IndexRoute,
  ApiAdCSlotIdRoute: ApiAdCSlotIdRoute,
  ApiAdISlotIdRoute: ApiAdISlotIdRoute,
  ApiPublicIcalTokenRoute: ApiPublicIcalTokenRoute,
  CSlugPIdRoute: CSlugPIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
