/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as EventsRouteImport } from './routes/events'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as MarketingUnsubscribeRouteImport } from './routes/marketing.unsubscribe'
import { Route as MarketingSubscribeRouteImport } from './routes/marketing.subscribe'
import { Route as MarketingConfirmRouteImport } from './routes/marketing.confirm'
import { Route as InviteTokenRouteImport } from './routes/invite.$token'
import { Route as EventsIdRouteImport } from './routes/events.$id'
import { Route as AuthStripeCallbackRouteImport } from './routes/auth.stripe-callback'
import { Route as AuthCallbackRouteImport } from './routes/auth.callback'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedSearchRouteImport } from './routes/_authenticated/search'
import { Route as AuthenticatedMapRouteImport } from './routes/_authenticated/map'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedCalendarRouteImport } from './routes/_authenticated/calendar'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin.index'
import { Route as AuthenticatedAdminUsersRouteImport } from './routes/_authenticated/admin.users'
import { Route as AuthenticatedAdminSponsorshipRouteImport } from './routes/_authenticated/admin.sponsorship'
import { Route as AuthenticatedAdminSetupRouteImport } from './routes/_authenticated/admin.setup'
import { Route as AuthenticatedAdminModerationRouteImport } from './routes/_authenticated/admin.moderation'
import { Route as AuthenticatedAdminAuditRouteImport } from './routes/_authenticated/admin.audit'
import { Route as ApiPublicIcalTokenRouteImport } from './routes/api/public/ical.$token'
import { Route as AuthenticatedEventsIdManageRouteImport } from './routes/_authenticated/events.$id.manage'
import { Route as AuthenticatedEventsIdCheckinMobileRouteImport } from './routes/_authenticated/events.$id.checkin-mobile'
import { Route as AuthenticatedEventsIdCheckinRouteImport } from './routes/_authenticated/events.$id.checkin'
import { Route as AuthenticatedEventsIdAnalyticsRouteImport } from './routes/_authenticated/events.$id.analytics'

const EventsRoute = EventsRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketingUnsubscribeRoute = MarketingUnsubscribeRouteImport.update({
  id: '/marketing/unsubscribe',
  path: '/marketing/unsubscribe',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketingSubscribeRoute = MarketingSubscribeRouteImport.update({
  id: '/marketing/subscribe',
  path: '/marketing/subscribe',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketingConfirmRoute = MarketingConfirmRouteImport.update({
  id: '/marketing/confirm',
  path: '/marketing/confirm',
  getParentRoute: () => rootRouteImport,
} as any)
const InviteTokenRoute = InviteTokenRouteImport.update({
  id: '/invite/$token',
  path: '/invite/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsIdRoute = EventsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => EventsRoute,
} as any)
const AuthStripeCallbackRoute = AuthStripeCallbackRouteImport.update({
  id: '/stripe-callback',
  path: '/stripe-callback',
  getParentRoute: () => AuthRoute,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/callback',
  path: '/callback',
  getParentRoute: () => AuthRoute,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSearchRoute = AuthenticatedSearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMapRoute = AuthenticatedMapRouteImport.update({
  id: '/map',
  path: '/map',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCalendarRoute = AuthenticatedCalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminUsersRoute = AuthenticatedAdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminSponsorshipRoute =
  AuthenticatedAdminSponsorshipRouteImport.update({
    id: '/sponsorship',
    path: '/sponsorship',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminSetupRoute = AuthenticatedAdminSetupRouteImport.update({
  id: '/setup',
  path: '/setup',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminModerationRoute =
  AuthenticatedAdminModerationRouteImport.update({
    id: '/moderation',
    path: '/moderation',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminAuditRoute = AuthenticatedAdminAuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const ApiPublicIcalTokenRoute = ApiPublicIcalTokenRouteImport.update({
  id: '/api/public/ical/$token',
  path: '/api/public/ical/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedEventsIdManageRoute =
  AuthenticatedEventsIdManageRouteImport.update({
    id: '/events/$id/manage',
    path: '/events/$id/manage',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedEventsIdCheckinMobileRoute =
  AuthenticatedEventsIdCheckinMobileRouteImport.update({
    id: '/events/$id/checkin-mobile',
    path: '/events/$id/checkin-mobile',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedEventsIdCheckinRoute =
  AuthenticatedEventsIdCheckinRouteImport.update({
    id: '/events/$id/checkin',
    path: '/events/$id/checkin',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedEventsIdAnalyticsRoute =
  AuthenticatedEventsIdAnalyticsRouteImport.update({
    id: '/events/$id/analytics',
    path: '/events/$id/analytics',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRouteWithChildren
  '/events': typeof EventsRouteWithChildren
  '/admin': typeof AuthenticatedAdminRouteWithChildren
  '/calendar': typeof AuthenticatedCalendarRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/map': typeof AuthenticatedMapRoute
  '/search': typeof AuthenticatedSearchRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/auth/stripe-callback': typeof AuthStripeCallbackRoute
  '/events/$id': typeof EventsIdRoute
  '/invite/$token': typeof InviteTokenRoute
  '/marketing/confirm': typeof MarketingConfirmRoute
  '/marketing/subscribe': typeof MarketingSubscribeRoute
  '/marketing/unsubscribe': typeof MarketingUnsubscribeRoute
  '/admin/audit': typeof AuthenticatedAdminAuditRoute
  '/admin/moderation': typeof AuthenticatedAdminModerationRoute
  '/admin/setup': typeof AuthenticatedAdminSetupRoute
  '/admin/sponsorship': typeof AuthenticatedAdminSponsorshipRoute
  '/admin/users': typeof AuthenticatedAdminUsersRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
  '/events/$id/analytics': typeof AuthenticatedEventsIdAnalyticsRoute
  '/events/$id/checkin': typeof AuthenticatedEventsIdCheckinRoute
  '/events/$id/checkin-mobile': typeof AuthenticatedEventsIdCheckinMobileRoute
  '/events/$id/manage': typeof AuthenticatedEventsIdManageRoute
  '/api/public/ical/$token': typeof ApiPublicIcalTokenRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRouteWithChildren
  '/events': typeof EventsRouteWithChildren
  '/calendar': typeof AuthenticatedCalendarRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/map': typeof AuthenticatedMapRoute
  '/search': typeof AuthenticatedSearchRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/auth/stripe-callback': typeof AuthStripeCallbackRoute
  '/events/$id': typeof EventsIdRoute
  '/invite/$token': typeof InviteTokenRoute
  '/marketing/confirm': typeof MarketingConfirmRoute
  '/marketing/subscribe': typeof MarketingSubscribeRoute
  '/marketing/unsubscribe': typeof MarketingUnsubscribeRoute
  '/admin/audit': typeof AuthenticatedAdminAuditRoute
  '/admin/moderation': typeof AuthenticatedAdminModerationRoute
  '/admin/setup': typeof AuthenticatedAdminSetupRoute
  '/admin/sponsorship': typeof AuthenticatedAdminSponsorshipRoute
  '/admin/users': typeof AuthenticatedAdminUsersRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
  '/events/$id/analytics': typeof AuthenticatedEventsIdAnalyticsRoute
  '/events/$id/checkin': typeof AuthenticatedEventsIdCheckinRoute
  '/events/$id/checkin-mobile': typeof AuthenticatedEventsIdCheckinMobileRoute
  '/events/$id/manage': typeof AuthenticatedEventsIdManageRoute
  '/api/public/ical/$token': typeof ApiPublicIcalTokenRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRouteWithChildren
  '/events': typeof EventsRouteWithChildren
  '/_authenticated/admin': typeof AuthenticatedAdminRouteWithChildren
  '/_authenticated/calendar': typeof AuthenticatedCalendarRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/map': typeof AuthenticatedMapRoute
  '/_authenticated/search': typeof AuthenticatedSearchRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/auth/stripe-callback': typeof AuthStripeCallbackRoute
  '/events/$id': typeof EventsIdRoute
  '/invite/$token': typeof InviteTokenRoute
  '/marketing/confirm': typeof MarketingConfirmRoute
  '/marketing/subscribe': typeof MarketingSubscribeRoute
  '/marketing/unsubscribe': typeof MarketingUnsubscribeRoute
  '/_authenticated/admin/audit': typeof AuthenticatedAdminAuditRoute
  '/_authenticated/admin/moderation': typeof AuthenticatedAdminModerationRoute
  '/_authenticated/admin/setup': typeof AuthenticatedAdminSetupRoute
  '/_authenticated/admin/sponsorship': typeof AuthenticatedAdminSponsorshipRoute
  '/_authenticated/admin/users': typeof AuthenticatedAdminUsersRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
  '/_authenticated/events/$id/analytics': typeof AuthenticatedEventsIdAnalyticsRoute
  '/_authenticated/events/$id/checkin': typeof AuthenticatedEventsIdCheckinRoute
  '/_authenticated/events/$id/checkin-mobile': typeof AuthenticatedEventsIdCheckinMobileRoute
  '/_authenticated/events/$id/manage': typeof AuthenticatedEventsIdManageRoute
  '/api/public/ical/$token': typeof ApiPublicIcalTokenRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/events'
    | '/admin'
    | '/calendar'
    | '/dashboard'
    | '/map'
    | '/search'
    | '/settings'
    | '/auth/callback'
    | '/auth/stripe-callback'
    | '/events/$id'
    | '/invite/$token'
    | '/marketing/confirm'
    | '/marketing/subscribe'
    | '/marketing/unsubscribe'
    | '/admin/audit'
    | '/admin/moderation'
    | '/admin/setup'
    | '/admin/sponsorship'
    | '/admin/users'
    | '/admin/'
    | '/events/$id/analytics'
    | '/events/$id/checkin'
    | '/events/$id/checkin-mobile'
    | '/events/$id/manage'
    | '/api/public/ical/$token'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/events'
    | '/calendar'
    | '/dashboard'
    | '/map'
    | '/search'
    | '/settings'
    | '/auth/callback'
    | '/auth/stripe-callback'
    | '/events/$id'
    | '/invite/$token'
    | '/marketing/confirm'
    | '/marketing/subscribe'
    | '/marketing/unsubscribe'
    | '/admin/audit'
    | '/admin/moderation'
    | '/admin/setup'
    | '/admin/sponsorship'
    | '/admin/users'
    | '/admin'
    | '/events/$id/analytics'
    | '/events/$id/checkin'
    | '/events/$id/checkin-mobile'
    | '/events/$id/manage'
    | '/api/public/ical/$token'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/events'
    | '/_authenticated/admin'
    | '/_authenticated/calendar'
    | '/_authenticated/dashboard'
    | '/_authenticated/map'
    | '/_authenticated/search'
    | '/_authenticated/settings'
    | '/auth/callback'
    | '/auth/stripe-callback'
    | '/events/$id'
    | '/invite/$token'
    | '/marketing/confirm'
    | '/marketing/subscribe'
    | '/marketing/unsubscribe'
    | '/_authenticated/admin/audit'
    | '/_authenticated/admin/moderation'
    | '/_authenticated/admin/setup'
    | '/_authenticated/admin/sponsorship'
    | '/_authenticated/admin/users'
    | '/_authenticated/admin/'
    | '/_authenticated/events/$id/analytics'
    | '/_authenticated/events/$id/checkin'
    | '/_authenticated/events/$id/checkin-mobile'
    | '/_authenticated/events/$id/manage'
    | '/api/public/ical/$token'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRouteWithChildren
  EventsRoute: typeof EventsRouteWithChildren
  InviteTokenRoute: typeof InviteTokenRoute
  MarketingConfirmRoute: typeof MarketingConfirmRoute
  MarketingSubscribeRoute: typeof MarketingSubscribeRoute
  MarketingUnsubscribeRoute: typeof MarketingUnsubscribeRoute
  ApiPublicIcalTokenRoute: typeof ApiPublicIcalTokenRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/events': {
      id: '/events'
      path: '/events'
      fullPath: '/events'
      preLoaderRoute: typeof EventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/marketing/unsubscribe': {
      id: '/marketing/unsubscribe'
      path: '/marketing/unsubscribe'
      fullPath: '/marketing/unsubscribe'
      preLoaderRoute: typeof MarketingUnsubscribeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/marketing/subscribe': {
      id: '/marketing/subscribe'
      path: '/marketing/subscribe'
      fullPath: '/marketing/subscribe'
      preLoaderRoute: typeof MarketingSubscribeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/marketing/confirm': {
      id: '/marketing/confirm'
      path: '/marketing/confirm'
      fullPath: '/marketing/confirm'
      preLoaderRoute: typeof MarketingConfirmRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invite/$token': {
      id: '/invite/$token'
      path: '/invite/$token'
      fullPath: '/invite/$token'
      preLoaderRoute: typeof InviteTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events/$id': {
      id: '/events/$id'
      path: '/$id'
      fullPath: '/events/$id'
      preLoaderRoute: typeof EventsIdRouteImport
      parentRoute: typeof EventsRoute
    }
    '/auth/stripe-callback': {
      id: '/auth/stripe-callback'
      path: '/stripe-callback'
      fullPath: '/auth/stripe-callback'
      preLoaderRoute: typeof AuthStripeCallbackRouteImport
      parentRoute: typeof AuthRoute
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/search': {
      id: '/_authenticated/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof AuthenticatedSearchRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/map': {
      id: '/_authenticated/map'
      path: '/map'
      fullPath: '/map'
      preLoaderRoute: typeof AuthenticatedMapRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/calendar': {
      id: '/_authenticated/calendar'
      path: '/calendar'
      fullPath: '/calendar'
      preLoaderRoute: typeof AuthenticatedCalendarRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/users': {
      id: '/_authenticated/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AuthenticatedAdminUsersRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/sponsorship': {
      id: '/_authenticated/admin/sponsorship'
      path: '/sponsorship'
      fullPath: '/admin/sponsorship'
      preLoaderRoute: typeof AuthenticatedAdminSponsorshipRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/setup': {
      id: '/_authenticated/admin/setup'
      path: '/setup'
      fullPath: '/admin/setup'
      preLoaderRoute: typeof AuthenticatedAdminSetupRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/moderation': {
      id: '/_authenticated/admin/moderation'
      path: '/moderation'
      fullPath: '/admin/moderation'
      preLoaderRoute: typeof AuthenticatedAdminModerationRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/audit': {
      id: '/_authenticated/admin/audit'
      path: '/audit'
      fullPath: '/admin/audit'
      preLoaderRoute: typeof AuthenticatedAdminAuditRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/api/public/ical/$token': {
      id: '/api/public/ical/$token'
      path: '/api/public/ical/$token'
      fullPath: '/api/public/ical/$token'
      preLoaderRoute: typeof ApiPublicIcalTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/events/$id/manage': {
      id: '/_authenticated/events/$id/manage'
      path: '/events/$id/manage'
      fullPath: '/events/$id/manage'
      preLoaderRoute: typeof AuthenticatedEventsIdManageRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/events/$id/checkin-mobile': {
      id: '/_authenticated/events/$id/checkin-mobile'
      path: '/events/$id/checkin-mobile'
      fullPath: '/events/$id/checkin-mobile'
      preLoaderRoute: typeof AuthenticatedEventsIdCheckinMobileRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/events/$id/checkin': {
      id: '/_authenticated/events/$id/checkin'
      path: '/events/$id/checkin'
      fullPath: '/events/$id/checkin'
      preLoaderRoute: typeof AuthenticatedEventsIdCheckinRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/events/$id/analytics': {
      id: '/_authenticated/events/$id/analytics'
      path: '/events/$id/analytics'
      fullPath: '/events/$id/analytics'
      preLoaderRoute: typeof AuthenticatedEventsIdAnalyticsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedAdminRouteChildren {
  AuthenticatedAdminAuditRoute: typeof AuthenticatedAdminAuditRoute
  AuthenticatedAdminModerationRoute: typeof AuthenticatedAdminModerationRoute
  AuthenticatedAdminSetupRoute: typeof AuthenticatedAdminSetupRoute
  AuthenticatedAdminSponsorshipRoute: typeof AuthenticatedAdminSponsorshipRoute
  AuthenticatedAdminUsersRoute: typeof AuthenticatedAdminUsersRoute
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
}

const AuthenticatedAdminRouteChildren: AuthenticatedAdminRouteChildren = {
  AuthenticatedAdminAuditRoute: AuthenticatedAdminAuditRoute,
  AuthenticatedAdminModerationRoute: AuthenticatedAdminModerationRoute,
  AuthenticatedAdminSetupRoute: AuthenticatedAdminSetupRoute,
  AuthenticatedAdminSponsorshipRoute: AuthenticatedAdminSponsorshipRoute,
  AuthenticatedAdminUsersRoute: AuthenticatedAdminUsersRoute,
  AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
}

const AuthenticatedAdminRouteWithChildren =
  AuthenticatedAdminRoute._addFileChildren(AuthenticatedAdminRouteChildren)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRouteWithChildren
  AuthenticatedCalendarRoute: typeof AuthenticatedCalendarRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedMapRoute: typeof AuthenticatedMapRoute
  AuthenticatedSearchRoute: typeof AuthenticatedSearchRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedEventsIdAnalyticsRoute: typeof AuthenticatedEventsIdAnalyticsRoute
  AuthenticatedEventsIdCheckinRoute: typeof AuthenticatedEventsIdCheckinRoute
  AuthenticatedEventsIdCheckinMobileRoute: typeof AuthenticatedEventsIdCheckinMobileRoute
  AuthenticatedEventsIdManageRoute: typeof AuthenticatedEventsIdManageRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRouteWithChildren,
  AuthenticatedCalendarRoute: AuthenticatedCalendarRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedMapRoute: AuthenticatedMapRoute,
  AuthenticatedSearchRoute: AuthenticatedSearchRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedEventsIdAnalyticsRoute: AuthenticatedEventsIdAnalyticsRoute,
  AuthenticatedEventsIdCheckinRoute: AuthenticatedEventsIdCheckinRoute,
  AuthenticatedEventsIdCheckinMobileRoute:
    AuthenticatedEventsIdCheckinMobileRoute,
  AuthenticatedEventsIdManageRoute: AuthenticatedEventsIdManageRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface AuthRouteChildren {
  AuthCallbackRoute: typeof AuthCallbackRoute
  AuthStripeCallbackRoute: typeof AuthStripeCallbackRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthCallbackRoute: AuthCallbackRoute,
  AuthStripeCallbackRoute: AuthStripeCallbackRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

interface EventsRouteChildren {
  EventsIdRoute: typeof EventsIdRoute
}

const EventsRouteChildren: EventsRouteChildren = {
  EventsIdRoute: EventsIdRoute,
}

const EventsRouteWithChildren =
  EventsRoute._addFileChildren(EventsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRouteWithChildren,
  EventsRoute: EventsRouteWithChildren,
  InviteTokenRoute: InviteTokenRoute,
  MarketingConfirmRoute: MarketingConfirmRoute,
  MarketingSubscribeRoute: MarketingSubscribeRoute,
  MarketingUnsubscribeRoute: MarketingUnsubscribeRoute,
  ApiPublicIcalTokenRoute: ApiPublicIcalTokenRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
